[package]
name = "deamon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
reqwest-blocking = "0.11"
serde = { version = "1", features = ["full"] }
serde_json = "1.0"